theme: jekyll-theme-cayman
person:
   first: Christina
   last: Krielesi

  email: p17krye@ionio.gr
  pdf: /data/cv.pdf
  src: https://github.com/chrikri/CV
  url: "chrikri.github.io"
  social:
    github: chrikri
  education:
  - school: Carnegie Mellon University
    location: Pittsburgh, Pennsylvania
    degree: Ph.D. in Computer Science
    dates: Aug 2014 -- May 2019 (expected)

  
